# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/GenericPipelines.Middlewares.slnx
    - name: Build
      run: dotnet build --no-restore --configuration Release src/GenericPipelines.Middlewares.slnx
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal src/GenericPipelines.Middlewares.slnx
    - name: Create the package
      run: dotnet pack --configuration Release --output out -p:Version=${{vars.NUGET_PACKAGE_VERSION}} src/GenericPipelines.Middlewares
    - name: Upload package
      uses: actions/upload-artifact@v4.6.2
      with:
        name: nuget-package
        path: out